"""CLI artifact contracts for failed HPC mappings and generated source provenance."""
import importlib.util
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest

_spec = importlib.util.spec_from_file_location('wave6_coverage_report', Path(__file__).parents[1] / 'coverage.py')
reporter = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(reporter)


class CoverageReportWave6Tests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name).resolve()
        subprocess.run(['git', 'init', '--quiet', str(self.root)], check=True)
        self.output = self.root / 'result.json'

    def report(self, *arguments):
        result = subprocess.run([sys.executable, reporter.__file__, '--root', str(self.root),
                                 '--output', str(self.output), *map(str, arguments)], capture_output=True, text=True)
        self.assertIn('Coverage evidence:', result.stdout, result.stderr)
        return result.returncode, json.loads(self.output.read_text())

    def hpc(self, source, name='A'):
        mix = self.root / 'mix'
        mix.mkdir(exist_ok=True)
        (mix / f'{name}.mix').write_text('Mix ' + json.dumps(str(source)) +
            ' 2026-09-07 07:50:58.313699322 UTC 123 8 [(1:1-1:4,ExpBox False)]')
        tix = self.root / 'input.tix'
        tix.write_text(f'Tix [TixModule "{name}" 123 1 [1]]')
        return ['--tix', tix, '--mix-dir', mix]

    def test_xml_rejects_missing_metrics_out_of_range_and_empty_modules(self):
        for xml, message in [
            ('<coverage><module name="A"/></coverage>', 'Missing HPC metric'),
            ('<coverage><module name="A"><exprs boxes="1" count="2"/></module></coverage>', 'Invalid HPC metric'),
            ('<coverage/>', 'no modules'),
            ('<coverage><module name="A"><exprs boxes="1" count="1"/><booleans boxes="1" count="0" true="1" false="0"/></module></coverage>', 'Invalid HPC metric'),
        ]:
            with self.subTest(xml=xml), self.assertRaisesRegex(ValueError, message):
                reporter.metrics(xml)

    def test_missing_explicit_manifest_remains_failure_in_report_only(self):
        (self.root / 'A.hs').write_text('module A where\na = 1\n')
        code, report = self.report('--scope-manifest', self.root / 'absent.json', '--report-only')
        self.assertEqual(code, 0)
        self.assertFalse(report['complete'])
        self.assertIn('Requested scope manifest does not exist', report['errors'])
        self.assertEqual(report['unmeasured_sources'], ['A.hs'])

    def test_no_matching_mix_is_reported_without_completeness(self):
        arguments = self.hpc(self.root / 'A.hs')
        (self.root / 'mix/A.mix').unlink()
        code, report = self.report(*arguments)
        self.assertEqual(code, 1)
        self.assertIn('No matching mix for A hash 123', report['errors'])

    def test_generated_module_requires_both_warning_and_cabal_declaration(self):
        # Generated source lives outside the repository inventory, as Cabal build output does.
        with tempfile.TemporaryDirectory() as generated:
            source = Path(generated) / 'Paths_fixture.hs'
            source.write_text('-- WARNING: This module was generated by Cabal.\n')
            arguments = self.hpc(source, 'Paths_fixture')
            cabal = self.root / 'fixture.cabal'
            cabal.write_text('name: fixture\nautogen-modules: Paths_fixture\n')
            _, report = self.report(*arguments)
            self.assertEqual(report['errors'], [])
            module = report['host_hpc'][0]
            self.assertEqual(module['scope'], 'generated-excluded')
            self.assertEqual(module['provenance'][0]['evidence'], 'fixture.cabal')
            self.assertFalse(report['complete'])  # Generated-only evidence cannot pass the repository gate.
            for content, declaration in [('ordinary source', True), (source.read_text(), False)]:
                source.write_text(content)
                cabal.write_text('name: fixture\n' + ('autogen-modules: Paths_fixture\n' if declaration else ''))
                with self.subTest(warning=content, declaration=declaration):
                    code, rejected = self.report(*arguments)
                    self.assertEqual(code, 1)
                    self.assertIn('Ambiguous or missing source mapping: Paths_fixture', rejected['errors'])

    def test_multiple_variants_do_not_hide_uncovered_runtime(self):
        source = self.root / 'src/A.hs'
        source.parent.mkdir()
        source.write_text('module A where\na = 1\n')
        arguments = self.hpc(source)
        code, report = self.report(*arguments, '--wasm-tix', self.root / 'input.tix', '--wasm-mix-dir', self.root / 'mix')
        self.assertEqual(code, 0)
        self.assertTrue(report['complete'])
        self.assertEqual(report['sources'][0]['required_runtimes'], ['host', 'wasm'])
        self.assertEqual(report['wasm']['status'], 'partial')
        self.assertTrue(report['host_hpc_complete'])
        (self.root / 'missing.tix').write_text('Tix [TixModule "A" 123 1 [0]]')
        code, incomplete = self.report(*arguments, '--wasm-tix', self.root / 'missing.tix', '--wasm-mix-dir', self.root / 'mix')
        self.assertEqual(code, 1)
        self.assertTrue(incomplete['host_hpc_complete'])
        self.assertFalse(incomplete['runtime_complete'])
        self.assertEqual(incomplete['unmeasured_sources'], [])

    def test_collector_outputs_must_belong_to_inventory(self):
        from contextlib import redirect_stdout
        import io
        from unittest.mock import patch
        for collector, payload, expected in [
            ('shell_evidence', {'missing.sh': {}}, 'Shell report contains non-shell inventory paths'),
            ('python_evidence', {'missing.py': {}}, 'Python report contains sources absent from inventory'),
            ('javascript_evidence', {'missing.js': {}}, 'Istanbul report contains sources absent from inventory'),
        ]:
            with self.subTest(collector=collector), patch.object(reporter, collector, return_value=payload), \
                    patch.object(sys, 'argv', ['coverage.py', '--root', str(self.root), '--output', str(self.output)]), \
                    redirect_stdout(io.StringIO()):
                self.assertEqual(reporter.main(), 1)
                report = json.loads(self.output.read_text())
                self.assertIn(expected, report['errors'])
                self.assertFalse(report['complete'])

    def test_validated_artifacts_attach_to_their_runtime_only(self):
        from contextlib import ExitStack, redirect_stdout
        import io
        from unittest.mock import patch
        for name in ['check.py', 'build.sh', 'types.d.ts']:
            (self.root / name).write_text('fixture\n')
        (self.root / 'review.md').write_text('Type declarations require compile validation.\n')
        manifest = self.root / 'scope.json'
        manifest.write_text(json.dumps({'validations': [{'path': 'types.d.ts', 'kind': 'declaration',
            'reason': 'Declaration compiler contract', 'evidence': 'review.md'}]}))
        measured = {'status': 'measured', 'complete': True}
        with ExitStack() as stack:
            for name, result in [('compile_evidence', {'types.d.ts': measured}),
                                 ('python_evidence', {'check.py': measured}),
                                 ('shell_evidence', {'build.sh': measured})]:
                stack.enter_context(patch.object(reporter, name, return_value=result))
            stack.enter_context(patch.object(sys, 'argv', ['coverage.py', '--root', str(self.root),
                '--scope-manifest', str(manifest), '--output', str(self.output)]))
            stack.enter_context(redirect_stdout(io.StringIO()))
            code = reporter.main()
        self.assertEqual(code, 0, self.output.read_text())
        report = json.loads(self.output.read_text())
        self.assertEqual(report['errors'], [])
        self.assertTrue(report['compile_validation_complete'])
        self.assertTrue(report['runtime_complete'])
        sources = {source['path']: source for source in report['sources']}
        for name, runtime in [('types.d.ts', 'compile'), ('check.py', 'python'), ('build.sh', 'shell')]:
            self.assertEqual(sources[name]['evidence'], {runtime: measured})

    def test_authenticated_equal_maps_project_complementary_ticks(self):
        from contextlib import redirect_stdout
        import hashlib
        import io
        from unittest.mock import patch
        source = self.root / 'A.hs'
        source.write_text('module A where\na = 1\n')
        mix = self.root / 'mix'
        mix.mkdir()
        artifacts = []
        arguments = ['coverage.py', '--root', str(self.root), '--output', str(self.output), '--mix-dir', str(mix)]
        layout = '8 [(1:1-1:2,ExpBox False),(2:1-2:4,ExpBox False)]'
        for name, fingerprint, ticks in [('one/A', 123, '1,0'), ('two/A', 456, '0,1')]:
            counter = self.root / (name.replace('/', '-') + '.tix')
            counter.write_text(f'Tix [TixModule "{name}" {fingerprint} 2 [{ticks}]]')
            directory = mix / name.split('/')[0]
            directory.mkdir()
            mapping = directory / 'A.mix'
            mapping.write_text('Mix ' + json.dumps(str(source)) + f' 2026-09-07 07:50:58.313699322 UTC {fingerprint} ' + layout)
            artifacts.extend([str(counter), str(mapping)])
            arguments.extend(['--tix', str(counter)])
        # Authentication is independently tested by host_projection_proof contracts;
        # this fixture verifies the report consumes that boundary result correctly.
        proof = {'artifacts': artifacts, 'sources': {'A.hs': hashlib.sha256(source.read_bytes()).hexdigest()},
                 'compiler': {'sha256': 'compiler-fingerprint', 'version': 'fixture'}}
        with patch.object(reporter, 'host_projection_proof', return_value=proof), \
                patch.object(sys, 'argv', arguments), redirect_stdout(io.StringIO()):
            code = reporter.main()
        self.assertEqual(code, 0, self.output.read_text())
        report = json.loads(self.output.read_text())
        evidence = report['sources'][0]['evidence']['host']
        self.assertEqual(len(evidence['modules']), 2)
        self.assertTrue(all(item['metrics']['exprs']['covered'] == 1 for item in evidence['modules']))
        self.assertEqual(evidence['projection']['metrics']['exprs']['covered'], 2)
        self.assertEqual(len(evidence['projection']['variants']), 2)
        self.assertTrue(evidence['complete'])
        self.assertEqual(report['errors'], [])
        (self.root / 'fixture.cabal').write_text('-- package name missing\nif arch(wasm32)\n  buildable: True\n')
        manifest = self.root / 'wasm-scope.json'
        manifest.write_text(json.dumps({'runtimes': [{'path': 'A.hs', 'required': ['wasm'],
            'reason': 'WASM-only fixture contract', 'evidence': 'fixture.cabal'}]}))
        with patch.object(reporter, 'host_projection_proof', return_value=proof), \
                patch.object(sys, 'argv', arguments + ['--scope-manifest', str(manifest)]), redirect_stdout(io.StringIO()):
            self.assertEqual(reporter.main(), 1)
        incomplete = json.loads(self.output.read_text())
        self.assertEqual(incomplete['errors'], [])
        self.assertEqual(incomplete['sources'][0]['evidence'], {'wasm': {'status': 'unmeasured'}})
