CREATE TABLE IF NOT EXISTS attempts (
  sequence INTEGER PRIMARY KEY AUTOINCREMENT,
  instance TEXT NOT NULL,
  step TEXT NOT NULL,
  attempt INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS effects (instance TEXT PRIMARY KEY, message TEXT NOT NULL);
