cabal-version: 3.0
name: quickstart-management
version: 0.1.0.0
build-type: Simple
license: BSD-3-Clause
library
  hs-source-dirs: src
  exposed-modules: Quickstart.Management
  default-language: GHC2024
  default-extensions: OverloadedStrings
  ghc-options: -Wall
  build-depends: base, aeson, text, time, mtl, servant, servant-cloudflare-workers, cloudflare-workers, quickstart-domain, quickstart-infrastructure

test-suite unit
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  hs-source-dirs: test/unit, test
  other-modules: Quickstart.ManagementSpec, Support.Management
  default-language: GHC2024
  default-extensions: OverloadedStrings
  ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N2
  build-tool-depends: testing-support:sydtest-discover-layer
  build-depends: base, quickstart-management, quickstart-infrastructure, quickstart-domain, servant, servant-cloudflare-workers, cloudflare-workers, mtl, sydtest, text, time
